/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.pstn.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * 电话号码对象
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner {
    @JsonProperty(value = "area", required = true)
    private Long area;

    @JsonProperty(value = "calling_party_area")
    private Long callingPartyArea;

    @JsonProperty(value = "calling_party_phone_number")
    private String callingPartyPhoneNumber;

    @JsonProperty(value = "extension_number")
    private String extensionNumber;

    @JsonProperty(value = "nick_name")
    private String nickName;

    @JsonProperty(value = "phone", required = true)
    private String phone;

    /**
     * @param area 电话区号 (required)
     * @param phone  (required)
     */
    public V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner(@NotNull Long area, @NotNull String phone) {
        this.area = area;
        this.phone = phone;
    }

    /**
     * @param area 电话区号 (required)
     */
    public V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner area(@NotNull Long area) {
        this.area = area;
        return this;
    }
    /**
     * @return area 电话区号
     **/
    public Long getArea() {
        return area;
    }

    /**
     * @param area 电话区号 (required)
     */
    public void setArea(Long area) {
        this.area = area;
    }
    /**
     * @param callingPartyArea 国家/地区代码。（例如：中国是86） 当前仅支持呼叫中国大陆、中国香港、美国的号码。
     */
    public V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner callingPartyArea(Long callingPartyArea) {
        this.callingPartyArea = callingPartyArea;
        return this;
    }
    /**
     * @return callingPartyArea 国家/地区代码。（例如：中国是86） 当前仅支持呼叫中国大陆、中国香港、美国的号码。
     **/
    public Long getCallingPartyArea() {
        return callingPartyArea;
    }

    /**
     * @param callingPartyArea 国家/地区代码。（例如：中国是86） 当前仅支持呼叫中国大陆、中国香港、美国的号码。
     */
    public void setCallingPartyArea(Long callingPartyArea) {
        this.callingPartyArea = callingPartyArea;
    }
    /**
     * @param callingPartyPhoneNumber 电话号码或固定电话总机号。
     */
    public V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner callingPartyPhoneNumber(String callingPartyPhoneNumber) {
        this.callingPartyPhoneNumber = callingPartyPhoneNumber;
        return this;
    }
    /**
     * @return callingPartyPhoneNumber 电话号码或固定电话总机号。
     **/
    public String getCallingPartyPhoneNumber() {
        return callingPartyPhoneNumber;
    }

    /**
     * @param callingPartyPhoneNumber 电话号码或固定电话总机号。
     */
    public void setCallingPartyPhoneNumber(String callingPartyPhoneNumber) {
        this.callingPartyPhoneNumber = callingPartyPhoneNumber;
    }
    /**
     * @param extensionNumber 
     */
    public V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner extensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber;
        return this;
    }
    /**
     * @return extensionNumber 
     **/
    public String getExtensionNumber() {
        return extensionNumber;
    }

    /**
     * @param extensionNumber 
     */
    public void setExtensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber;
    }
    /**
     * @param nickName 
     */
    public V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner nickName(String nickName) {
        this.nickName = nickName;
        return this;
    }
    /**
     * @return nickName 
     **/
    public String getNickName() {
        return nickName;
    }

    /**
     * @param nickName 
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    /**
     * @param phone  (required)
     */
    public V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner phone(@NotNull String phone) {
        this.phone = phone;
        return this;
    }
    /**
     * @return phone 
     **/
    public String getPhone() {
        return phone;
    }

    /**
     * @param phone  (required)
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner v1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner = (V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner) o;
        return Objects.equals(this.area, v1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner.area) &&
            Objects.equals(this.callingPartyArea, v1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner.callingPartyArea) &&
            Objects.equals(this.callingPartyPhoneNumber, v1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner.callingPartyPhoneNumber) &&
            Objects.equals(this.extensionNumber, v1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner.extensionNumber) &&
            Objects.equals(this.nickName, v1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner.nickName) &&
            Objects.equals(this.phone, v1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner.phone);
    }

    @Override
    public int hashCode() {
        return Objects.hash(area, callingPartyArea, callingPartyPhoneNumber, extensionNumber, nickName, phone);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1MeetingMeetingIdPhoneCalloutPostRequestPhoneNumbersInner {\n");
        sb.append("    area: ").append(toIndentedString(area)).append("\n");
        sb.append("    callingPartyArea: ").append(toIndentedString(callingPartyArea)).append("\n");
        sb.append("    callingPartyPhoneNumber: ").append(toIndentedString(callingPartyPhoneNumber)).append("\n");
        sb.append("    extensionNumber: ").append(toIndentedString(extensionNumber)).append("\n");
        sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
        sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

