/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.user_manager.model;

import java.util.*;

import com.fasterxml.jackson.annotation.*;

/**
 * V1UsersUseridGet200ResponseDepartmentListInner
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1UsersUseridGet200ResponseDepartmentListInner {
    @JsonProperty(value = "department_id")
    private String departmentId;

    @JsonProperty(value = "department_name")
    private String departmentName;

    /**
     */
    public V1UsersUseridGet200ResponseDepartmentListInner() {
    }

    /**
     * @param departmentId 
     */
    public V1UsersUseridGet200ResponseDepartmentListInner departmentId(String departmentId) {
        this.departmentId = departmentId;
        return this;
    }
    /**
     * @return departmentId 
     **/
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * @param departmentId 
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    /**
     * @param departmentName 
     */
    public V1UsersUseridGet200ResponseDepartmentListInner departmentName(String departmentName) {
        this.departmentName = departmentName;
        return this;
    }
    /**
     * @return departmentName 
     **/
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * @param departmentName 
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1UsersUseridGet200ResponseDepartmentListInner v1UsersUseridGet200ResponseDepartmentListInner = (V1UsersUseridGet200ResponseDepartmentListInner) o;
        return Objects.equals(this.departmentId, v1UsersUseridGet200ResponseDepartmentListInner.departmentId) &&
            Objects.equals(this.departmentName, v1UsersUseridGet200ResponseDepartmentListInner.departmentName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(departmentId, departmentName);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1UsersUseridGet200ResponseDepartmentListInner {\n");
        sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
        sb.append("    departmentName: ").append(toIndentedString(departmentName)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

