/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.user_manager.model;

import java.util.*;

import com.fasterxml.jackson.annotation.*;

/**
 * V1UsersOpenIdToUseridPost200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1UsersOpenIdToUseridPost200Response {
    @JsonProperty(value = "userid_list")
    private List<V1UsersOpenIdToUseridPost200ResponseUseridListInner> useridList;

    /**
     */
    public V1UsersOpenIdToUseridPost200Response() {
    }

    /**
     * @param useridList 转换成功的该自建应用所在企业下的userid、open_id对应关系列表。
     */
    public V1UsersOpenIdToUseridPost200Response useridList(List<V1UsersOpenIdToUseridPost200ResponseUseridListInner> useridList) {
        this.useridList = useridList;
        return this;
    }
    /**
     * @return useridList 转换成功的该自建应用所在企业下的userid、open_id对应关系列表。
     **/
    public List<V1UsersOpenIdToUseridPost200ResponseUseridListInner> getUseridList() {
        return useridList;
    }

    /**
     * @param useridList 转换成功的该自建应用所在企业下的userid、open_id对应关系列表。
     */
    public void setUseridList(List<V1UsersOpenIdToUseridPost200ResponseUseridListInner> useridList) {
        this.useridList = useridList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1UsersOpenIdToUseridPost200Response v1UsersOpenIdToUseridPost200Response = (V1UsersOpenIdToUseridPost200Response) o;
        return Objects.equals(this.useridList, v1UsersOpenIdToUseridPost200Response.useridList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(useridList);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1UsersOpenIdToUseridPost200Response {\n");
        sb.append("    useridList: ").append(toIndentedString(useridList)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

