/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.user_manager.model;

import java.util.*;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1UsersInviteActivatePostRequest
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1UsersInviteActivatePostRequest {
    @JsonProperty(value = "userid_list", required = true)
    private List<String> useridList;

    /**
     * @param useridList 未激活的账号列表，最多支持传100个 (required)
     */
    public V1UsersInviteActivatePostRequest(@NotNull List<String> useridList) {
        this.useridList = useridList;
    }

    /**
     * @param useridList 未激活的账号列表，最多支持传100个 (required)
     */
    public V1UsersInviteActivatePostRequest useridList(@NotNull List<String> useridList) {
        this.useridList = useridList;
        return this;
    }
    /**
     * @return useridList 未激活的账号列表，最多支持传100个
     **/
    public List<String> getUseridList() {
        return useridList;
    }

    /**
     * @param useridList 未激活的账号列表，最多支持传100个 (required)
     */
    public void setUseridList(List<String> useridList) {
        this.useridList = useridList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1UsersInviteActivatePostRequest v1UsersInviteActivatePostRequest = (V1UsersInviteActivatePostRequest) o;
        return Objects.equals(this.useridList, v1UsersInviteActivatePostRequest.useridList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(useridList);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1UsersInviteActivatePostRequest {\n");
        sb.append("    useridList: ").append(toIndentedString(useridList)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

