/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.user_manager.model;

import java.util.*;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1UsersOpenIdToUseridPostRequest
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1UsersOpenIdToUseridPostRequest {
    @JsonProperty(value = "sdkid", required = true)
    private String sdkid;

    /**
     * @param sdkid 第三方应用的sdkid。需要转换的open_id应为腾讯会议为该三方应用提供的open_id。 (required)
     */
    public V1UsersOpenIdToUseridPostRequest(@NotNull String sdkid) {
        this.sdkid = sdkid;
    }

    /**
     * @param sdkid 第三方应用的sdkid。需要转换的open_id应为腾讯会议为该三方应用提供的open_id。 (required)
     */
    public V1UsersOpenIdToUseridPostRequest sdkid(@NotNull String sdkid) {
        this.sdkid = sdkid;
        return this;
    }
    /**
     * @return sdkid 第三方应用的sdkid。需要转换的open_id应为腾讯会议为该三方应用提供的open_id。
     **/
    public String getSdkid() {
        return sdkid;
    }

    /**
     * @param sdkid 第三方应用的sdkid。需要转换的open_id应为腾讯会议为该三方应用提供的open_id。 (required)
     */
    public void setSdkid(String sdkid) {
        this.sdkid = sdkid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1UsersOpenIdToUseridPostRequest v1UsersOpenIdToUseridPostRequest = (V1UsersOpenIdToUseridPostRequest) o;
        return Objects.equals(this.sdkid, v1UsersOpenIdToUseridPostRequest.sdkid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sdkid);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1UsersOpenIdToUseridPostRequest {\n");
        sb.append("    sdkid: ").append(toIndentedString(sdkid)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

