/*
 * 腾讯会议OpenAPI
 * SAAS版RESTFUL风格API
 *
 * The version of the OpenAPI document: v1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.tencentcloudapi.wemeet.service.user_manager.model;

import java.util.*;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.*;
import org.jetbrains.annotations.NotNull;

/**
 * V1UsersAccountStatisticsGet200Response
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class V1UsersAccountStatisticsGet200Response {
    @JsonProperty(value = "ai_account_details")
    private List<V1UsersAccountStatisticsGet200ResponseAiAccountDetailsInner> aiAccountDetails;

    @JsonProperty(value = "user_account_details")
    private List<V1UsersAccountStatisticsGet200ResponseUserAccountDetailsInner> userAccountDetails;

    @JsonProperty(value = "user_count")
    private Long userCount;

    /**
     */
    public V1UsersAccountStatisticsGet200Response() {
    }

    /**
     * @param aiAccountDetails ai账号类型使用对象（商业版不返回）
     */
    public V1UsersAccountStatisticsGet200Response aiAccountDetails(List<V1UsersAccountStatisticsGet200ResponseAiAccountDetailsInner> aiAccountDetails) {
        this.aiAccountDetails = aiAccountDetails;
        return this;
    }
    /**
     * @return aiAccountDetails ai账号类型使用对象（商业版不返回）
     **/
    public List<V1UsersAccountStatisticsGet200ResponseAiAccountDetailsInner> getAiAccountDetails() {
        return aiAccountDetails;
    }

    /**
     * @param aiAccountDetails ai账号类型使用对象（商业版不返回）
     */
    public void setAiAccountDetails(List<V1UsersAccountStatisticsGet200ResponseAiAccountDetailsInner> aiAccountDetails) {
        this.aiAccountDetails = aiAccountDetails;
    }
    /**
     * @param userAccountDetails 账号类型使用对象
     */
    public V1UsersAccountStatisticsGet200Response userAccountDetails(List<V1UsersAccountStatisticsGet200ResponseUserAccountDetailsInner> userAccountDetails) {
        this.userAccountDetails = userAccountDetails;
        return this;
    }
    /**
     * @return userAccountDetails 账号类型使用对象
     **/
    public List<V1UsersAccountStatisticsGet200ResponseUserAccountDetailsInner> getUserAccountDetails() {
        return userAccountDetails;
    }

    /**
     * @param userAccountDetails 账号类型使用对象
     */
    public void setUserAccountDetails(List<V1UsersAccountStatisticsGet200ResponseUserAccountDetailsInner> userAccountDetails) {
        this.userAccountDetails = userAccountDetails;
    }
    /**
     * @param userCount 当前用户数
     */
    public V1UsersAccountStatisticsGet200Response userCount(Long userCount) {
        this.userCount = userCount;
        return this;
    }
    /**
     * @return userCount 当前用户数
     **/
    public Long getUserCount() {
        return userCount;
    }

    /**
     * @param userCount 当前用户数
     */
    public void setUserCount(Long userCount) {
        this.userCount = userCount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1UsersAccountStatisticsGet200Response v1UsersAccountStatisticsGet200Response = (V1UsersAccountStatisticsGet200Response) o;
        return Objects.equals(this.aiAccountDetails, v1UsersAccountStatisticsGet200Response.aiAccountDetails) &&
            Objects.equals(this.userAccountDetails, v1UsersAccountStatisticsGet200Response.userAccountDetails) &&
            Objects.equals(this.userCount, v1UsersAccountStatisticsGet200Response.userCount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(aiAccountDetails, userAccountDetails, userCount);
    }

    /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1UsersAccountStatisticsGet200Response {\n");
        sb.append("    aiAccountDetails: ").append(toIndentedString(aiAccountDetails)).append("\n");
        sb.append("    userAccountDetails: ").append(toIndentedString(userAccountDetails)).append("\n");
        sb.append("    userCount: ").append(toIndentedString(userCount)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

